export const lsqLeadFieldNames = {
  project: "mx_Origin_Project",
  leadNumber: "ProspectAutoId",
  source: "Source",
  category: null,
  prospectStage: "ProspectStage",
  newLead: null,
  createdOn: "CreatedOn",
  origin: "Origin",
  agencyName: null,
  medium: null,
  createdDate: "CreatedOnDate",
  createdTime: "CreatedOnTime",
  phone: "Phone",
  remarks: null,
  activityEvent: null,
  ownerIdName: "OwnerIdName",
  campaign: "SourceCampaign",
  stage: "ProspectStage",
  agency: "mx_Agency_Name",
  subSource: "mx_First_Sub_Source",
};
